# Generated by Django 3.0.5 on 2023-02-01 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom_cl', models.CharField(max_length=30)),
                ('prenom_cl', models.CharField(max_length=30)),
                ('mail', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=30)),
                ('telephone', models.IntegerField()),
                ('adresse', models.CharField(max_length=30)),
            ],
        ),
    ]
